# Generated by Django 2.2.4 on 2022-09-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
