# Generated by Django 2.2.4 on 2022-09-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='No Value', max_length=255),
            preserve_default=False,
        ),
    ]
