# Generated by Django 2.2.4 on 2022-10-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='users_who_visit',
            field=models.ManyToManyField(related_name='visit_user', to='first_app.User'),
        ),
    ]
