# Generated by Django 2.2.4 on 2022-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='No Notes', max_length=255),
            preserve_default=False,
        ),
    ]
